version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_date:/var/lib/postgresql/data/

    env_file:
      - .env.db
    ports:
      - 5432:5432
volumes:
  postgres_date:
