# Generated by Django 4.1.7 on 2023-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("womanshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.CharField(default="active", max_length=255, null=True),
        ),
    ]
