# Generated by Django 4.1.7 on 2023-04-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("womanshop", "0002_alter_userprofile_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
