# Generated by Django 4.1.7 on 2023-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("womanshop", "0012_brand_category_color_size_style_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
