# Generated by Django 4.1.7 on 2023-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("womanshop", "0013_alter_product_vendor_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
