# Generated by Django 4.1.7 on 2023-06-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("womanshop", "0014_product_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
