# Generated by Django 4.1.7 on 2023-06-11 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("womanshop", "0015_product_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="stock",
        ),
    ]
