# Generated by Django 4.1.7 on 2023-07-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("womanshop", "0018_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
